version: "3.4"

services:
  postgresql: 
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "postgresPsw"
    ports:
      - "432:5432"
    restart: always
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
volumes:
  postgresql_data:
    driver: local
networks:
  default:    
    name: eventsourcingnetwork
    external: true
